### ISSUE TITLE
IOS not working

### ISSUE THREAD

**Issue by GiviMAD** [jmRicardo/capacitor-audio-permission#1]
Buenas, he tratado de usar el plugin en IOS, pero lanza el error:
Error: "AudioPermissions" plugin is not implemented on iOS.

Se le ocurre cual puede ser el origen?

**Comment by jmRicardo** [comment]
¡Hola buenas! Me darias un poco mas info, que versión de iOS estas usando,
si estas usando simulador o no. Tenes instalada la ultima version que
subi!? supongo que si.

Hago unas pruebas cuando me pases esa info.

**Comment by GiviMAD** [comment]
Era un error mio. Creo q por haber añadido la dependencia en optionalDependencies, despues de cambiarla a dependencies y ejecutar cap sync, la librería funciona perfectamente, soy capaz de pedir permisos y a partir de ahi la user media api, todo parece funcionar correctamente, muchas gracias por tu trabajo!
